http-port: 23940 #port to run http proxy on
api-port: 23941 #api port
threads: 50 #线程数，指一次扫描多少个节点
source: ./sub/source/sub_merge_yaml.yml #你的输入文件名, 注意必须是clash配置文件格式, 此处是input.yaml
outfile: ./sub/source/check.yaml #你的输出文件名, 注意输出文件也是clash配置文件格式, 此处是output.yaml
#test-url: http://www.gstatic.com/generate_204
test-url: https://www.youtube.com/s/player/23010b46/player_ias.vflset/en_US/remote.js #延迟测试地址, 可以更改
timeout: 3000 #测试的超时界限, timeout in miliseconds
